### ISSUE TITLE
Isn't this a public way to release python package to ROS?

### ISSUE THREAD

**Issue by wkentaro** [ros-infrastructure/ros_release_python#16]
I'm releasing to [python-gdown](https://pypi.python.org/pypi/gdown) to use it in ROS, and tried to release as a ROS package: https://github.com/ros/rosdistro/pull/14935.
After doing that, I found this repo, and it is a standard way of releasing python packages to ROS by osrf: for examaple catkin-tools, wstool and catkin_pkg.

I followed the instruction in README but blocked by being asked the password to upload the deb package:
```
-- Uploading package to apt repositories...
# dput -u -c ../ros_release_python/resources/dput.cf ros-bootstrap deb_dist/python-gdown_3.2.6-1_source.changes
Uploading to ros-bootstrap (via scp to repos.ros.org):
rosbuild@repos.ros.org's password:
```

**So, is that not possible to release python package to ROS by ROS contributors?**
I also browsed [reprepro-uploader](https://github.com/ros-infrastructure/reprepro-updater) but felt `ros_release_python` is the better way.

(The python package is hosted here: https://github.com/wkentaro/gdown)

**Comment by dirk-thomas** [comment]
No, the script in this repository is only being used to release Python packages for ROS which are ROS distribution agnostic. Any ROS package should be released for a specific ROS distribution instead (via bloom).

**Comment by wkentaro** [comment]
python-gdown is a pypi package and it is ROS agnostic, but I'd like to use it in other ROS packages.
In this case, should I make the python package into ROS package, and release by bloom?

**Comment by dirk-thomas** [comment]
Yes, that is the only way supported for releasing ROS packages.

**Comment by dirk-thomas** [comment]
You might want to take a look at [catkin_pip](https://github.com/asmodehn/catkin_pip) from @asmodehn.

Or you might want to consider to release the package into Debian if you want it to be available in future Debian / Ubuntu versions (outside of ROS).

**Comment by wkentaro** [comment]
I see. Thank you.
