### ISSUE TITLE
Restricting 20.04 to python3.

### ISSUE THREAD

**Issue by nuclearsandwich** [ros-infrastructure/ros_release_python#34]
For the upcoming 20.04-based ROS releases we are trying to keep Python 2 packages out of our bootstrap repository. Currently this script releases packages into all suites specified in the `Suite` option for each package.
There is some support in the `--include` parameter for a separate `Suite3` option which is only used on python3 targets but that support does not currently extend to the regular release scripts here and stdeb itself does not currently support this config clause and so does not generate Suite3-aware .changes files.

One workaround for that problem is to immediately use the `--include` option to push python3 packages into Suite3 targets after making a new release. For example:
```
## in stdeb.cfg
# Suite: xenial bionic
# Suite3: focal

# Publish a new package to all suites in `Suite` and pypi.
ros_release_python --upload

# Now include it in suites only in Suite3
ros_release_python --include --upload deb3
```

This works but it will be very slow due to the added publishing cycle.
It also means that if Suite3 support is ever added to stdeb we may not notice when our older suites that are currently python2 and python3 stop receiving python3 updates because they are not present in Suite3. We could add all suites to Suite3 which would slow the script down further, although because the snapshot and publish is only run once per include target it would only make a bad problem worse rather than making a bad problem excruciating.

**Comment by dirk-thomas** [comment]
The following repos have been updated to specify `Suite3`:
* ros-infrastructure/catkin_pkg#271
* ros-infrastructure/rosdistro#148
