### ISSUE TITLE
failure to register with PyPi does not cause a failure

### ISSUE THREAD

**Issue by wjwwood** [ros-infrastructure/ros_release_python#5]
If you don't have permission to release to pypi then the registration will fail, but the `ros_release_python` script does seem to fail on that. This lead to me releasing new versions of vcstools and wstool into debian and not into pypi without noticing.

We need to figure out how to catch this case and report it in a meaningful way to the user.

I would give out from this problem but I don't have the terminal history where it occurred. I'll add it if I run into it again.

**Comment by dirk-thomas** [comment]
I just tried this again (on Xenial) and PyPi returns a 401 which leads to a return code of 1 for the python invocation. Therefore I will close this ticket.

If it is still a problem for you please comment with more information and this can be reopened.
