### ISSUE TITLE
support conflicts between python2 and python3 debs

### ISSUE THREAD

**Issue by wjwwood** [ros-infrastructure/ros_release_python#9]
Either automatically, or explicitly in the `stdeb.cfg` files, we should allow setting the Conflicts rule between the python2 and python3 debs of the same package.

See: https://github.com/ros-infrastructure/rospkg/issues/71

Currently stdeb cannot do this: https://github.com/astraw/stdeb/issues/81

**Comment by dirk-thomas** [comment]
This has been addressed for all ROS packages in the meantime: ros/rosdistro#7090
